### ISSUE TITLE
Lambda Support

### ISSUE THREAD

**Issue by gocursor** [eclipse-windowbuilder/windowbuilder#176]
WindowBuilder does not recognize lambda expressions, for example:
    addHelpListener(e -> System.out.println("Help!"));

Support for lambda expressions should be added to enable transition to new coding style where a lot of code is written in lambdas.

WindowBuilder Version: 1.9.7.202112020939

**Comment by wimjongman** [comment]
I agree. Are you able to supply a patch? I can help you get started.

**Comment by wimjongman** [comment]
![image](https://user-images.githubusercontent.com/180969/159117758-91360172-38c3-4a74-b45d-cb5448f042d8.png)

**Comment by gocursor** [comment]
Please help me get started: How do I setup the development environment? Which IDE/version should I use? Are the repos located here at GitHub or are they somewhere else and just replicated here on GitHub? Do I need C/C++ compiler?

**Comment by wimjongman** [comment]
We have an automated development environment setup script and explanations here:

https://github.com/eclipse/windowbuilder/blob/master/CONTRIBUTING.md

**Comment by vogella** [comment]
That would be really useful, I stopped using WB due to this. Not being able to use lambdas is a no-go these days.

**Comment by ptziegler** [comment]
The whole thing was a little bit more complicated than expected but lambda expressions, method references and the SWT factory methods  should now be properly recognized.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/f12fd8af-2a33-46dd-93d0-064130d50de1)

**Comment by rosennej** [comment]
It does not work for me, a Swing radio button.

**Comment by ptziegler** [comment]
No need to post the message twice. The problem was already brought up in #729 and is caused by the plugin containing this functionality not being installed properly. It should be fixed by #734 but still needs to be merged back into the master.
