### ISSUE TITLE
Remove copies from GEF in Windowbuilder and use latest libraries

### ISSUE THREAD

**Issue by vogella** [eclipse-windowbuilder/windowbuilder#186]
org.eclipse.wb.core contains copies of GEF and draw2d. As GEF classic is currently revived we should remove this usage and use the latest release from GEF which will be created by https://github.com/eclipse/gef-classic/issues/40

**Comment by vogella** [comment]
This would also allow to style WB once https://github.com/eclipse/gef-classic/pull/140 lands in GEF.

**Comment by vogella** [comment]
@ptziegler could you help here?

**Comment by amitin** [comment]
Please note that GEF classes in WB were not the same as Eclipse GEF at that time. I don't remember the details now, but we replaced standard GEF with our own implementation due to lack of some functionality in the standard GEF. So replacing it with modern Eclipse GEF won't be easy at all. And I actually think that it's not so worth.

**Comment by ptziegler** [comment]
As @amitin mentioned, one of the big challenges is going to be the separation of the WB extensions from the original GEF code.

Given the scope of this task, I think it makes sense to split this migration into two parts: Draw2D and GEF.

I've started looking at the Draw2D classes and while it's going to be a lot of work, I think it's definitely possible to get the changes here reintegrated into GEF.

Luckily, there are quite a lot of JUnit tests for both Draw2D and GEF. So if all of them remain green, I think there's a good chance that the functionality of WB remains unaffected.

**Comment by vogella** [comment]
Thanks @ptziegler, every step that removes duplicated code would be great. IIRC I did not manage to activate all existing tests, so if you discover some which are not yet included, please check if they also can be enabled.

**Comment by vogella** [comment]
@ptziegler thanks for working actively on this. I close this issue, I don't think it is needed for your work
