### ISSUE TITLE
Replace Guava Lists.newArrayList(); with new ArrayList<>();

### ISSUE THREAD

**Issue by vogella** [eclipse-windowbuilder/windowbuilder#270]
AFAICS Guava Lists.newArrayList(); simply delegates to new ArrayList<>(); in WB therefore we can use this standard Java construct.

**Comment by ptziegler** [comment]
With #663, the last remaining dependency to Guava has been removed. We now either use the corresponding Java methods directly or Commons Collections (for e.g. BidiMaps).
