### ISSUE TITLE
New Error The project cannot be built until its prerequisite org.eclipse.wb.jdt.fragment is built.

### ISSUE THREAD

**Issue by vogella** [eclipse-windowbuilder/windowbuilder#284]
In the latest WindowBuilder master I get the following error message:

 Description	Resource	Path	Location	Type
The project cannot be built until its prerequisite org.eclipse.wb.jdt.fragment is built. Cleaning and building all projects is recommended	org.eclipse.wb.dev		Unknown	Java Problem

The only changes in master from last week (there I did not see this error), were the commits from @howlger 

423160263a3b1ba75773282ed8da6859375e6843
82954c4de6009cd4c78b1bf0785db78a0f16f023

Both seemed unrelated. If I do clean project sufficiently (2-3 times) the error goes away but reappears.

@HannesWell are you aware of any changes in PDE? org.eclipse.wb.jdt.fragment is a fragment so I do not see why org.eclipse.wb.dev should depend on it.

**Comment by mickaelistria** [comment]
> I bet @mickaelistria could tell us how to trace the iterations of the project builders.

In Launch Configuration dialog > Trace > Enable Tracing > org.eclipse.core.resources; check what seems interesting. See also https://github.com/mickaelistria/eclipse-ide-parallel-builds-demo I used to generate some Gantt charts a while ago, but it's not just plug'n'play IIRC you need to modify some code to get everything working.

**Comment by ptziegler** [comment]
Is this problem still relevant? I've never seen an error like this show up in the workspace. So I assume whatever caused this has long been fixed.

**Comment by ptziegler** [comment]
The fragment was never included in any release and has been removed by #734. Whatever caused this issue should've become obsolete, now that it is gone.
