### ISSUE TITLE
Windowbuilder (Swing) hangs Eclipse on opening class

### ISSUE THREAD

**Issue by farmboy0** [eclipse-windowbuilder/windowbuilder#310]
When i open my ui class generated with windowbuilder and switch to design tab  it now hangs indefinitely and Eclipse becomes completely unresponsive.

This also happened before on other occasions (when the designer still opened my ui class). One point it always happened is when choosing Preview from the right click menu.

No errors are created in the error log.

I have tried to delete windowbuilder settings from the workspace without any effect.
The class is completely generated, no manual edits.

![Screenshot_20220712_234322](https://user-images.githubusercontent.com/2206262/178602199-c1b4a39a-d160-4fca-8322-ff5274c4a974.png)

**Comment by farmboy0** [comment]
This is on Eclipse 4.24 with WindowBuilder 1.9.8

**Comment by lcaron** [comment]
Thank you for your report.

Can you please post the source code that hangs WB ?

**Comment by farmboy0** [comment]
[PortageView.java.txt](https://github.com/eclipse/windowbuilder/files/9124600/PortageView.java.txt)
While when trying it again I can open the editor now in design view eclipse still hangs when doing a preview.

**Comment by ptziegler** [comment]
This problem might now be fixed with 7fbbce2a30ce225cfb391ce2864c152705417589
@farmboy0  Can you check whether the same issue appears with the latest build?

**Comment by farmboy0** [comment]
Where can I find a build that includes this commit?

**Comment by ptziegler** [comment]
Hm... normally I'd have said from [here](https://download.eclipse.org/windowbuilder/lastgoodbuild/). But the latest nightly build is from last month...

I think this is related to #398, because of which the Jenkins can't upload the latest artifacts to our update site.

@vogella Can you have a look at the build script and check whether it's using Java 17?
I don't have access to the Jenkins, so I can't do it myself :(

**Comment by farmboy0** [comment]
Unfortuantely it cant be installed on 4.26:

Cannot complete the install because one or more required items could not be found.
  Software being installed: WindowBuilder Swing Designer 1.12.0.202304301104 (org.eclipse.wb.swing.feature.feature.group 1.12.0.202304301104)
  Missing requirement: Swing Designer 1.9.1.202304301104 (org.eclipse.wb.swing 1.9.1.202304301104) requires 'osgi.bundle; org.eclipse.draw2d 3.13.0' but it could not be found
  Cannot satisfy dependency:
    From: WindowBuilder Swing Designer 1.12.0.202304301104 (org.eclipse.wb.swing.feature.feature.group 1.12.0.202304301104)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wb.swing [1.9.1.202304301104,1.9.1.202304301104]

**Comment by merks** [comment]
You can make that available by adding one of these sites to the available sites:

- https://download.eclipse.org/tools/gef/classic/latest
- https://download.eclipse.org/releases/2023-06

You can always find such sites relatively easily:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring#How_to_find_a_P2_repository_at_Eclipse_using_the_Repository_Explorer

**Comment by ptziegler** [comment]
> You can make that available by adding one of these sites to the available sites:

Though I think it would make the installation more convenient, if we add those bundles either to the feature or directly to the update site. Having to first search for all dependent p2 repositories sounds like a real hassle.

**Comment by billykd4dpb** [comment]
thanks for the info i tryed the nightly build it did no good would not install here are some screen shots showing the issues have never been able to install any nightly builds FYI i am runnung ubuntu 22.04
![Screenshot from 2023-05-13 12-46-16](https://github.com/eclipse/windowbuilder/assets/108770658/d369d504-708f-460f-9794-b82be3286948)
![Screenshot from 2023-05-13 12-49-29](https://github.com/eclipse/windowbuilder/assets/108770658/0c8d4f62-f092-492c-8dff-b1562d414f4f)

![Screenshot from 2023-05-13 12-50-06](https://github.com/eclipse/windowbuilder/assets/108770658/2a82990c-9d52-445b-b52b-a9e4051f44d6)
![Screenshot from 2023-05-13 12-50-51](https://github.com/eclipse/windowbuilder/assets/108770658/c387eb2d-a8c2-48e6-924b-370eadc870ee)
I hope this can be fixed soon

**Comment by billykd4dpb** [comment]
Many thanks i will try the nightly build I managed to change to x11 with not much affect I managed to finish my coding i was working on with no crashes but please note when i click on the option that says preview you design without running your design eclipse crashes almost immediately will keep you posted

**Comment by byteit101** [comment]
I would like to confirm that installing 1.13 solved this hang for me

**Comment by lcaron** [comment]
Great news, thank you for your feedback (and mega-giga-extra thanks to @ptziegler & @merks )

**Comment by ptziegler** [comment]
There's a good change that this has been fixed with 7fbbce2a30ce225cfb391ce2864c152705417589.

@farmboy0 can you try out the latest release and check if the problem still shows up on your side:
https://download.eclipse.org/windowbuilder/updates/release/latest/

**Comment by farmboy0** [comment]
Seems to work with 1.12.0
