### ISSUE TITLE
When tab order set, new tabbable controls  not recognized

### ISSUE THREAD

**Issue by deej79** [eclipse-windowbuilder/windowbuilder#358]
If you set tab order on a form, then add a new control, tab order doesn't recognize it. You have to remove the tab order call in the code.
Either: when adding a control which can be tabbed to, if tab order is set add it to the end;
             - OR -
           when selected tab order, check if additional controls since it was last set, and add them.

Thanks.

**Comment by ptziegler** [comment]
Fixed with #572. As you suggested, if a tab order has been set, any new controls will be automatically added to the end.
