### ISSUE TITLE
XWT Plugin incompatible with latest Eclipse platform

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder#362]
WB uses the seemingly custom Eclipse plugin org.eclipse.e4.xwt as an embedded jar. This plugin is not compatible with the latest version, given that it still uses classes such as SWTObservables, which were removed with
https://github.com/eclipse-platform/eclipse.platform.ui/commit/c44f8d77f42cbcc17a0da3daabbb16bcd8745a86

Because WB uses the compiled classes, this problem only shows up at runtime (such as the XWT tests). The options are to:

- Recompile the jar against the Eclipse and fix any dependency issues.
- Get the plugin into the Eclipse platform.

**Comment by vogella** [comment]
If that is the case and nobody complained about this, I would think that the active user base of XWT and WB is very small and would suggest to retire XWT support. If someone shows up to enable XWT again, this person  could revert the removal and make XWT support work again.

@ptziegler WDYT?

**Comment by lcaron** [comment]
Fine for me too !

**Comment by ptziegler** [comment]
No objections from my side, either. We only use the Swing builder, so it doesn't affect us.

I only noticed it after checking the tests, because it's not even possible to open the design page of an XWT application, without running into a NoClassDefFoundError caused by a reference to the TableTree widget.

Which means that the user base is either still running an older Eclipse version or already found a way around this problem.

**Comment by vogella** [comment]
> Which means that the user base is either still running an older Eclipse version or already found a way around this problem.

Or we have no users using XWT with WB. AFAIK XWT is relatively low in usuage.

@ptziegler do you want to prepare a PR for the removal of XWT?

**Comment by ptziegler** [comment]
Given that it was relatively straightforward to integrate the latest XWT release, I considered better to keep supporting XWT. All the noticeable incompatibilities with recent Eclipse versions have been resolved.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/77af3e1b-a7d9-461d-a69a-25b5a27e742b)

**Comment by merks** [comment]
I'm sure someone will be thankful, but they'll likely forget to thank you!
