### ISSUE TITLE
What is the maximum width and height of JFrame In design window?

### ISSUE THREAD

**Issue by scott0122** [eclipse-windowbuilder/windowbuilder#384]
What is the maximum width and height of JFrame in design window?
I drag the mouse to change the width and height of JFrame to 4096x2048. The width and height of JFrame will automatically change back to 30xx * 18xx after draging.

Is this a bug?

**Comment by ptziegler** [comment]
That sounds definitely like a bug. In principle, there should be no hard limit on how big the frame can be.

I've created a simple class using the JFrame template and if I extend the frame horizontally, I can change the width arbitrarily. Just when I try to do the same vertically, the frame snaps back to the height of the client area.

Even if I change the height in the source page, the value is not taken over when switching back to the design page.

**Comment by scott0122** [comment]
@ptziegler 

Is there a timeline for fixing this bug?

> That sounds definitely like a bug. In principle, there should be no hard limit on how big the frame can be.
> 
> I've created a simple class using the JFrame template and if I extend the frame horizontally, I can change the width arbitrarily. Just when I try to do the same vertically, the frame snaps back to the height of the client area.
> 
> Even if I change the height in the source page, the value is not taken over when switching back to the design page.

**Comment by ptziegler** [comment]
> Is there a timeline for fixing this bug?

This project is run by volunteers and this issue is currently not very high on my bucket list. So if this is an urgent problem, I think your best chance is if you're able to submit a patch for it. I will find the time to review it and get it merged into the master.

That being said, I think the issue lies somewhere within the GraphicalViewer, or more generally with our GEF fork. So this is the first point where I'd start looking.

It might also be that this issue is going to be resolved together with #186. But that's something I've just started with, so it's nowhere near completion.

**Comment by scott0122** [comment]
Can you please advise which class should I track from? My development environment has been set up. But I have no idea which class should be tracked from for this bug.

> > Is there a timeline for fixing this bug?
> 
> This project is run by volunteers and this issue is currently not very high on my bucket list. So if this is an urgent problem, I think your best chance is if you're able to submit a patch for it. I will find the time to review it and get it merged into the master.
> 
> That being said, I think the issue lies somewhere within the GraphicalViewer, or more generally with our GEF fork. So this is the first point where I'd start looking.
> 
> It might also be that this issue is going to be resolved together with #186. But that's something I've just started with, so it's nowhere near completion.

**Comment by ptziegler** [comment]
> Can you please advise which class should I track from?

The way WindowBuilder creates the preview is by constructing a JFrame instance and then taking a screenshot. So the relevant classes are the `setBounds()` in the JFrame, JFrameInfo and the Figure class.

It think it would be interesting to see whether this value is updated correctly, after the JFrame has been resized.

**Comment by ptziegler** [comment]
I had a look at this issue again and I think this is hard limitation of Java/Swing.

Take this class for example:
```
public class Test {
	public static void main(String[] args) {
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setBounds(100, 100, 10000, 10000);
		frame.setVisible(true);
	}
}
```

If you run this class (without WindowBuilder, just as a normal Java application), then the frame will be maximized and take up your entire screen (which most likely has a smaller resolution than 10000x10000). So to answer your initial question:
The maximum width and height of a JFrame is defined by (java.awt.)Toolkit.getScreenSize().

Which means there is little that can be fixed on our site. The documentation should probably be updated, to include this limitation and the preview in the design page should also be limited to that size.

**Comment by ptziegler** [comment]
(As a side-note: A similar limitation seems to also exist for SWT)

**Comment by ptziegler** [comment]
Fixed with #482. The limitation of the Swing components to the screen resolution has been removed.

**Comment by scott0122** [comment]
@ptziegler 

Not working


https://github.com/eclipse-windowbuilder/windowbuilder/assets/39105828/23859802-13c1-489b-b2a0-f88d6ff9e6ce

**Comment by ptziegler** [comment]
Hm... it looks like the nightly build containing this fix wasn't pushed to the update site due to a sporadic test failure.
Can you try again with the latest build?
https://download.eclipse.org/windowbuilder/updates/nightly/latest

**Comment by scott0122** [comment]
@ptziegler 

I compiled and tested it myself using the source on github. I have looked at the source code. It has been corrected.
