### ISSUE TITLE
Rectangle doesn't enclose selected Swing component

### ISSUE THREAD

**Issue by billykd4dpb** [eclipse-windowbuilder/windowbuilder#453]
Not sure how to phrase this but when you place a item on the jframe the items sizing handles are not over the item but above it as shown on the screenshot
![Screenshot from 2023-05-17 23-03-46](https://github.com/eclipse-windowbuilder/windowbuilder/assets/108770658/232fbe47-8f6b-4d4f-ba2b-cd7bd66e34cb)

**Comment by ptziegler** [comment]
Thanks for reporting this bug. It seems like this issue was introduced  with 39b287514511e1ecb7b8f32396db21e204d1463c.

From what I remember, I did that due to test failures on Linux. In short, I'll roll back this revision. Then I'll see which test cases are still failing.

**Comment by ptziegler** [comment]
Fixed with c1b8716. The problematic revision has been reverted.
