### ISSUE TITLE
1.12.0 smoke test

### ISSUE THREAD

**Issue by wimjongman** [eclipse-windowbuilder/windowbuilder#460]
I have installed the latest from https://download.eclipse.org/windowbuilder/updates/nightly/latest/ and created a new SWT Window.

I got this:

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/180969/0b744072-83da-4739-905c-f1447550a433)

**Comment by ptziegler** [comment]
@wimjongman 

Does this issue still show up with the 1.13 milestone?
If so, can you check what your `java.version` system property is set to?

We internally check the version via this method in commons-lang. Zero is defined as the error value:
```
    /**
     * <p>
     * Gets the Java version as a <code>float</code>.
     * </p>
     * 
     * <p>
     * Example return values:
     * </p>
     * <ul>
     * <li><code>1.2f</code> for Java 1.2
     * <li><code>1.31f</code> for Java 1.3.1
     * </ul>
     * 
     * <p>
     * The field will return zero if {@link #JAVA_VERSION} is <code>null</code>.
     * </p>
     * 
     * @since 2.0
     */
    public static final float JAVA_VERSION_FLOAT = getJavaVersionAsFloat();
```

**Comment by wimjongman** [comment]
No, I don't see it anymore.
