### ISSUE TITLE
WindowBuilder was not able to parse source list.setBounds

### ISSUE THREAD

**Issue by ManiRaj-1** [eclipse-windowbuilder/windowbuilder#472]
Unable to parse source.

WindowBuilder was not able to parse source list.setBounds(499, 269, 1, 1);. 

line: 23 The method initialize() from the type mywindow is never used locally
line: 26 JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized
line: 26 JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized
line: 27 JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized
line: 27 JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized
line: 37 list cannot be resolved

Possible reasons: •Using old versions of libraries in your Java project.
•Not all required dependencies exist in your Java project.
•Compilation errors in your Java project.
•Use of conflicting variable name such as com, org, net, edu, java, or javax.
•Bug in WindowBuilder.

**Comment by ptziegler** [comment]
Can you upload the Java file that's causing problems? (Ideally as a text/zip file, not by pasting the code directly into the comment)

What version of WindowBuilder are you using?

Just from the error message alone, I'm suspecting a compile error within the Java file. But without further information, that's all I can currently say.
> line: 37 list cannot be resolved

**Comment by ptziegler** [comment]
I assume those issues reported here are the result of compile errors in the Java source code. Most likely due to an incomplete module-info.java. With the upcoming 1.14.0, this file should be managed automatically, for the most part.
