### ISSUE TITLE
Unknown GUI Toolkit

### ISSUE THREAD

**Issue by coderjhaw** [eclipse-windowbuilder/windowbuilder#473]
Good day guys! I just want to build window application in eclipse but I encounter this error. Please help. TIA.

<img width="658" alt="image" src="https://github.com/eclipse-windowbuilder/windowbuilder/assets/26891162/c6d2aa1e-93db-4535-9cd8-971bf19b645b">

**Comment by ptziegler** [comment]
Can you provide the source code that's causing problems?
What WindowBuilder version are you using?

**Comment by MalyarAFK** [comment]
Got the exact same problem too!

**Comment by harrydeore** [comment]
yeah, same here. It's the exact problem

**Comment by ptziegler** [comment]
@harrydeore Can you provide a small code snippet?

**Comment by Siddharth-thakur10** [comment]
Got the same problem when i downloaded window builder for the first time
the below is my code

```
package xyz;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

public class Dframe extends JFrame {

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Dframe frame = new Dframe();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public Dframe() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		setContentPane(contentPane);
	}

}
```
and here is the image
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/78204657/46531fae-237b-4d86-a43e-36c87aaba621)

**Comment by ptziegler** [comment]
@Siddharth-thakur10 
The snippet on its own looks fine, so I assume there is an issue within your Java project. Does the class contain compilation errors? If so, WindowBuilder won't be able to understand the code.

**Comment by ptziegler** [comment]
I assume those issues reported here are the result of compile errors in the Java source code. Most likely due to an incomplete module-info.java. With the upcoming 1.14.0, this file should be managed automatically, for the most part.
