### ISSUE TITLE
WindowBuilder fails to install for basic Java IDE via dropins

### ISSUE THREAD

**Issue by dhmartin** [eclipse-windowbuilder/windowbuilder#545]
I know the use of dropins folder is not very popular nowadays, but i tend to use it because it provides a fast systemwide install using scripts. I have used this procedure for eclipse Java IDE with WindowBuilder, but it's failing since eclipse 2023-06 with WindowBuilder 12. Actually, it does behave as usual with eclipse JEE 2023-06!

I'm using both W10 and Linux Ubuntu 22.04, properly updated. Neither the OS nor the JDK version (adoptium) seem to make any difference.

The procedure:
- Unzip/untar eclipse.
- Create dir dropins/WindowBuilder and unzip WindowBuilder-Updates-1.12.0.zip
- Remove p2 root files in dropins/WindowBuilder
- Start eclipse (removed .eclipse and .p2 for testing purposes)
- Check for WB icon / Check with New XXX wizards for WindowBuilder
- Maybe restart eclipse and retry: makes no difference

As I said:
- Java IDE 2023-03 + WB 11: OK
- Java IDE 2023-06 + WB 12: fail
- JEE IDE 2023-06 + WB 12: OK

Last week I also tried with Java IDE 2023-09 M2, with no luck.

I have copied config listings before and after populating the dropins folder in both cases. I may keep using eclipse JEE, but I hope this may help.

David
[eclipse202306jee.conf-000.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344294/eclipse202306jee.conf-000.txt)
[eclipse202306jee.conf-dropins.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344296/eclipse202306jee.conf-dropins.txt)
[eclipse202306.conf-000.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344299/eclipse202306.conf-000.txt)
[eclipse202306.conf-dropins.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344300/eclipse202306.conf-dropins.txt)

**Comment by ptziegler** [comment]
I've just tried to start both WB 11 and 12 with the Eclipse 2023-09 M1, but neither works. So I find it weird that it did with the 2023-03.
I also have the suspicion that this is a general issue in Equinox/P2 because when I look at the log, I can see following error being thrown several times (and the same with 1.12.0, of course):
> Error: file:/home/patrick/eclipse/dropins/WindowBuilder-Updates-1.11.0/ is not a valid extension location because it already contains a standard p2 repository file.

If you remove everything but the features and plugins folder, the dropin mechanism seems to work again. So I think that problem is not exclusive to WindowBuilder.

Can you try and run `./eclipse -clean -consoleLog` via the command line to see if you get the same error?

**Comment by dhmartin** [comment]
That's right. I have always got that "contains p2 file" error if I don't remove the extra files from the root of the WB updates ZIP.

OK, let's try: M1 or M2?… I suppose you tried "eclipse Java IDE", not "eclipse JEE IDE"
No luck: no WB icon, no new WB wizard. ¿Did you really succeed?

See both setup log and config files:
[eclipse202309M2.conf-dropins.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12346924/eclipse202309M2.conf-dropins.txt)
[eclipse202309M2.setuplog.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12346925/eclipse202309M2.setuplog.txt)

Remember that I told you that the same procedure does work if using "eclipse JEE IDE 2023-06". Actually, to make me sure, I have just tried the exact same steps for "eclipse JEE IDE 2023-09 M2" and it works: both icon and WB wizard are visible there straight out of the box!

**Comment by dhmartin** [comment]
It seems not…:

`
dmartin@ebano:~/tmp/borrar$ grep "org.apache.commons.collections" eclipse202306.conf-dropins.txt
dmartin@ebano:~/tmp/borrar$ grep "org.apache.commons.collections" eclipse202306jee.conf-dropins.txt
org.apache.commons.collections (3.2.2.v20220405-1659) "Apache Commons Collections" [Resolved]
Id: org.apache.commons.collections, Version: 3.2.2.v20220405-1659, Location: reference:file:plugins/org.apache.commons.collections_3.2.2.v20220405-1659.jar
dmartin@ebano:~/tmp/borrar$
`

And you're right 🙂: I repeated the same procedure with "Java IDE 2023-09 M2", I unjared org.apache.commons.collections_3.2.2.v20220405-1659.jar in a separate dropin's folder and voila! I got both the WB toolbar icon and the wizard; and I had no problems to create a new Java project, add an application window class and switch to see the design tab.

So, now… Should I patch my installation scripts or wait a bit for a fix in WB13?

**Comment by ptziegler** [comment]
> So, now… Should I patch my installation scripts or wait a bit for a fix in WB13?

As a temporary solution, I would go with manually adding the missing bundles. The fix itself shouldn't be too difficult. I just have to double-check if there are other dependencies that need to be added to the update site.

**Comment by dhmartin** [comment]
Thanks a lot! It's been a nuisance these moths dealing with eclipse old, new, Java and JEE version swapping. Not to say all the testing time invested...  🤓

**Comment by ptziegler** [comment]
It seems like only commons-collections was missing. The fix should be available with the next nightly build or the upcoming M3.
