### ISSUE TITLE
Issue with windowBuilder of Eclipse workspace

### ISSUE THREAD

**Issue by GakBibi** [eclipse-windowbuilder/windowbuilder#574]
![Capture](https://github.com/eclipse-windowbuilder/windowbuilder/assets/145546763/04f99e5a-d2e0-407c-a6f9-f84d758a9cd1)

How can i sold this issue?

**Comment by ptziegler** [comment]
Can you provide the source code of your Java class? As the error message says, your class doesn't seem to be a valid UI class, so WindowBuilder is unable to process it.

In general, I'd suggest creating the class using the "New" wizard and then add whatever UI components you need. 
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/22f9ea38-d573-4ba9-afe0-2ff0beaff26c)

**Comment by ptziegler** [comment]
I assume those issues reported here are the result of compile errors in the Java source code. Most likely due to an incomplete module-info.java. With the upcoming 1.14.0, this file should be managed automatically, for the most part.
