### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by adidiot** [eclipse-windowbuilder/windowbuilder#579]
Using Eclipse 4.29, Ubuntu 22.10, with Oracle JDK 21
Create a SWT/JFace project and a shell ...

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/90908346/a8551ced-14c1-421a-b5f0-1a65b0127b1d)

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/90908346/c902cc77-6b35-4905-811f-8fe150ad7efc)

Thanks!

**Comment by ptziegler** [comment]
Fixed with #581. The fix will be available with the 1.14. For the time being, your best bet is to install the upcoming nightly build or to use an older Java version (17-20).
