### ISSUE TITLE
Update README with a cool looking screenshot

### ISSUE THREAD

**Issue by vogella** [eclipse-windowbuilder/windowbuilder#580]
If I have to show WB to people which do not have it installed I have to point to https://eclipse.dev/windowbuilder/ which looks really outdated (at least the used version of Eclipse with its ugly blue background, etc).

Maybe a cool modern screenshot can be displayed via the readme and the project page can point to this repo?

@ptziegler feel free to close this issue in case you disagree.

**Comment by vogella** [comment]
For example, see https://github.com/eclipse-platform

**Comment by ptziegler** [comment]
I agree... The main page looks a little lackluster. I'll see if I can come up with something good.
