### ISSUE TITLE
Unknown GUI toolkit  error

### ISSUE THREAD

**Issue by ShimiyanaJakroda** [eclipse-windowbuilder/windowbuilder#592]
Am trying to open Jframes in Eclipse under SwingDesigner but its giving me Unknown GUI toolkit error what can be the problem.

![Capture](https://github.com/eclipse-windowbuilder/windowbuilder/assets/138066464/7140f4a8-3087-4630-a730-cc87ccc02b2f)

**Comment by ptziegler** [comment]
Can you provide the source code?

**Comment by khangg113** [comment]
> Contributor

i have a that problem too.
this is my code.
package view;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

public class QLSVView extends JFrame {

	private JPanel contentPane;
	

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					QLSVView frame = new QLSVView();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public QLSVView() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		setContentPane(contentPane);
	}

}

**Comment by khangg113** [comment]
[code.zip](https://github.com/eclipse-windowbuilder/windowbuilder/files/12890767/code.zip)

**Comment by khangg113** [comment]
> Can you provide the source code?

i have a that problem too, pls help me

**Comment by MalyarAFK** [comment]
Got the exact same problem!

**Comment by ptziegler** [comment]
@MalyarAFK Can you provide a screenshot and/or the code you're using?

At least in case of @khangg113, the problem was a result of compilation errors due to working with a modular project without adding the Swing module as a dependency.

Otherwise I can only speculate on what the problem is, you're running into.

**Comment by miguel4vlar** [comment]
Hi, I also have problem with that. Here's my code:
![Uploading Screenshot 2023-10-26 120711.png…]()

**Comment by ptziegler** [comment]
@miguel4vlar I think the screenshot wasn't uploaded properly.

**Comment by ptziegler** [comment]
I assume those issues reported here are the result of compile errors in the Java source code. Most likely due to an incomplete module-info.java. With the upcoming 1.14.0, this file should be managed automatically, for the most part.
