### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by khangg113** [eclipse-windowbuilder/windowbuilder#600]
![Screenshot (136)](https://github.com/eclipse-windowbuilder/windowbuilder/assets/147803521/defe6bf2-9455-473d-8bd3-576c6a60c025)

**Comment by ptziegler** [comment]
You're using [Modules](https://dev.java/learn/modules/intro/). Either add "java.desktop" to your "module-info.java" or delete the file entirely.

**Comment by ptziegler** [comment]
I'm closing this issue, as it isn't an issue with WindowBuilder, but rather just the way modules work with Java 9 and onwards.

The comment above should be sufficient to resolve the compilation errors:

> You're using [Modules](https://dev.java/learn/modules/intro/). Either add "java.desktop" to your "module-info.java" or delete the file entirely.
