### ISSUE TITLE
WindowBuilder generates code with "Shell" and "Display" as unresolved types

### ISSUE THREAD

**Issue by github-gs666** [eclipse-windowbuilder/windowbuilder#613]

**Comment by github-gs666** [comment]
I created a "WindowBuilderTest" project in Eclipse 2023-09 using File->New->other->WindowBuilder->SWT Designer->SWT/Jface Java Project

In the "src" directory of the generated project, I created an Application Window
File->New->other->WindowBuilder->SWT Designer->SWT/Jface Java Project->SWT->Application Window. This is the code it generated:
===============================
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
// **ALL** of the imports have  the error "The type **_<import>_** is not accessible"

public class WindowBuilderTestMain {

	protected Shell shell; **//Shell cannot be resolved to a type**

	/**
	 * Launch the application.
	 * @param args
	 */
	public static void main(String[] args) {
		try {
			WindowBuilderTestMain window = new WindowBuilderTestMain();
			window.open();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Open the window.
	 */
	public void open() {
		Display display = Display.getDefault(); **_//Shell cannot be resolved to a type_**
		createContents();
		shell.open();
		shell.layout();
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}
	}

	/**
	 * Create contents of the window.
	 */
	protected void createContents() {
		shell = new Shell();
		shell.setSize(450, 300);
		shell.setText("SWT Application");

	}

}

===============================

**Comment by github-gs666** [comment]
Here is the Build Path of the project:
![WindowBuilderTest Build Path](https://github.com/eclipse-windowbuilder/windowbuilder/assets/147398075/88686f3a-d293-4260-b829-589d51d4f95c)

**Comment by github-gs666** [comment]
Sorry to have bothered anybody who have spent time on this. I "Cleaned" the project. The unresolved imports cleared up and the program ran. I still don't know what happened and how "Project->Clean" did. That'll likely remain one of the mysteries of my life :-).

**Comment by github-gs666** [comment]
Sorry, but I have to re-open this issue. I accidentally deleted the project and when I re-created it the problem came back and "Clean" didn't work this time.

**Comment by ptziegler** [comment]
>  ALL of the imports have the error "The type is not accessible"

Are you using Java [modules](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) by any chance?

I.e. does your project contain a module-info.java:
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/4866a21b-ae17-47f4-b1b5-c3572d2705f1)

If so, you either have to adapt this file to require the SWT bundle or instead simply delete it.

**Comment by github-gs666** [comment]
Wow - I deleted the module-info.java and it fixed the problem. I'll have to look into module-info.java and figure out what it does :-). Thanks a lot for your quick help. This has been driving me crazy.

**Comment by ptziegler** [comment]
I assume those issues reported here are the result of compile errors in the Java source code. Most likely due to an incomplete module-info.java. With the upcoming 1.14.0, this file should be managed automatically, for the most part.

**Comment by github-gs666** [comment]
Actually, someone on this list solved it right away. The 2023-09 version started generating a "module-info" file by default. Defining that file makes the programmer specify any dependencies explicitly. The helpful suggestion was to delete the module-info file. Doing that made all the problems go away. 

I personally feel that it was a mistake to check the "module-info" option in the New Project form by default. It sure causes confusion for people like me who had no idea what the file does. I just assumed that it must be a good thing, since it was the default. I was wrong.

**Comment by ptziegler** [comment]
> I personally feel that it was a mistake to check the "module-info" option in the New Project form by default. It sure causes confusion for people like me who had no idea what the file does.

I agree, the modular system is quite obscure and the error is not very helpful.. Hopefully, with the upcoming WindowBuilder version this will be something you no longer to worry about.
