### ISSUE TITLE
Double-clicking a WindowBuilder runnable jar gives JVM Launcher Error/Java Exception

### ISSUE THREAD

**Issue by github-gs666** [eclipse-windowbuilder/windowbuilder#614]
I have a Window Builder program (“WordleSolver”) that works when I run it within eclipse Version: 2023-09 (4.29.0) Build id: 20230907-1323. I believe that the project was originally created in a previous release.

I exported the program as a Runnable Jar.

THE PROBLEM:
Double-clicking on the runnable jar results in a Java Virtual Machine Launcher error dialog saying “A Java Exception has occurred”. I haven’t been able to figure out what the exception is or where it occurred.

NOTES:

The jar works fine when executed from the command line with “java -jar WordleSolver.jar”.
Command line Java version:
C:\Temp>java -version
java version "16" 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

When I exported it as a runnable jar, it gave me the seemingly ever-present “finished with warnings” message. Below  is the message with a summary of the details:
===========
JAR export finished with warnings. See details for additional information.
  Exported with compile warnings: WordleSolver/src/pkgWordleSolver/WordleSolverMain.java
JAR export finished with warnings. See details for additional information.
  Exported with compile warnings: WordleSolver/src/pkgWordleSolver/WordleSolverMain.java
  duplicate entry: .api_description
  duplicate entry: .api_description
  duplicate entry: about.html
  duplicate entry: about.html

Same “duplicate entry” message for the following IDs:
...
plugin.properties, about_files/LICENSE-2.0.txt, .api_description,  entry: .options,  about.html, plugin.properties, plugin.xml,   .api_description, .options, plugin.properties, plugin.xml,  .api_description, about.html, plugin.properties, .api_description, about.html, .api_description, .options, about.html, plugin.properties, .api_description, .options, about.html, plugin.properties, .api_description, .options, about.html, plugin.properties, plugin.xml, about.html, .api_description, .options, about.html, plugin.properties, plugin.xml
...
===========

The Build Path for the project is in the following screenshot.
Any ideas would be welcome.

![WordleSolver Build Path](https://github.com/eclipse-windowbuilder/windowbuilder/assets/147398075/dbc3fedc-a346-4d0e-b86b-b995ff136c5e)

**Comment by ptziegler** [comment]
> Double-clicking on the runnable jar results in a Java Virtual Machine Launcher error dialog saying “A Java Exception has occurred”. I haven’t been able to figure out what the exception is or where it occurred.

>The jar works fine when executed from the command line with “java -jar WordleSolver.jar”.

From what I can tell, the jar itself is valid, if you are able to launch it from the command line. My best guess is that the JDK that is used when double-clicking isn't the one that is used in the command line. That said, I fail to see how this is then related to WindowBuilder, given that the problem would show up on _any_ exported jar.

> When I exported it as a runnable jar, it gave me the seemingly ever-present “finished with warnings” message.
> duplicate entry: .api_description
> duplicate entry: .api_description
> duplicate entry: about.html
> duplicate entry: about.html

I would expect that to be normal. In the end, you create a runnable jar containing all required Eclipse dependencies. Meaning all bundles like e.g. JFace and SWT are merged into a single archive. If some of those bundles contain the same file (e.g. plugin.xml, license text), it's only natural that they overwrite each other.

**Comment by ptziegler** [comment]
I'm closing this one. The "duplicate entry" warnings are expected when shading multiple jars into one. If the same file is contained by multiple jars then one overwrites the other.

If the widget works fine inside the editor but not when exported, then this sounds unrelated to WindowBuilder and something that should be raised with the [PDE](https://github.com/eclipse-pde/eclipse.pde) project.
