### ISSUE TITLE
Unknown GUI toolkit

### ISSUE THREAD

**Issue by Almusavveer** [eclipse-windowbuilder/windowbuilder#620]
I was trying to create a Java Application using window Builder and it show this error 
![issue](https://github.com/eclipse-windowbuilder/windowbuilder/assets/67317335/9bbdaf9d-3e8b-4d39-9169-981df489e902)

**Comment by ptziegler** [comment]
You're using Java 9 [modules](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) without requiring `java.desktop`. This causes the compile errors in `Login_Page.java`, which is also the reason why WindowBuilder can't understand the code.

You either have to update your `module-info.java` accordingly or simply delete it, if you don't want to use modules.
I'm closing this issue as it this is normal Java behavior and not really related to WindowBuilder itself.
