### ISSUE TITLE
design windows not appear

### ISSUE THREAD

**Issue by GullSher** [eclipse-windowbuilder/windowbuilder#664]
### Discussed in https://github.com/eclipse-windowbuilder/windowbuilder/discussions/656

<div type='discussions-op-text'>

<sup>Originally posted by **shathulan** December 11, 2023</sup>
i am doing my work in office pc and i am coping that folder to my usb, after i am trying to open that folder where codes are working but design menu not appearing . i did java swing with eclipse.</div>

**Comment by ptziegler** [comment]
How did you with this problem?
