### ISSUE TITLE
having trouble with eclipse.ide

### ISSUE THREAD

**Issue by pleasehelpmepoop** [eclipse-windowbuilder/windowbuilder#694]
i am trying to create a login page however this IDE either just doesnt function ( i know eclipse is bottom of the barrel these days dont hate on me for using it) but id like to know why im getting these  errors.  below are attached images of my errors and my code.

![Screenshot 2024-01-24 231403](https://github.com/eclipse-windowbuilder/windowbuilder/assets/157743487/c77b175b-7955-4787-b2df-48596ad79512)
![Screenshot 2024-01-24 231416](https://github.com/eclipse-windowbuilder/windowbuilder/assets/157743487/29439205-76c0-4628-9e14-d90e8790fa9a)

![Screenshot 2024-01-24 231952](https://github.com/eclipse-windowbuilder/windowbuilder/assets/157743487/e2e18eb7-377c-4cc8-b306-df88b71fe6d4)

**Comment by ptziegler** [comment]
In general, there seems to be something wrong with your module-info.java. Which is why Java is unable to resolve the Swing classes.
Is there a reason why you have this file? If you don't want/need a modular project, you can simply remove those files.

The other problems are the compilation errors, which are already highlighted in the Java editor.

> i know eclipse is bottom of the barrel these days dont hate on me for using it

I mean.. unlike commercial products, there is a very easy way to improve the IDE. But those are just my humble two cents.

**Comment by pleasehelpmepoop** [comment]
I get hated on in most other forums for using eclipse because to them
free=garbage so I added that in there to get past that and not have to dig
through BS comments to find the helpful ones.

**Comment by pleasehelpmepoop** [comment]
Would you be able to show me the solution to fix this?  I have no real clue
how to fix it.

**Comment by ptziegler** [comment]
Let's start with the basic problems:

1)

If you're not sure how Java modules work, I would suggest deleting the module-info.java files...

2)

```
public class AdminLogin {
    private class AdminLogin extends JFrame {
        ...
    }
}
```
You can't have inner classes with the same name. Remove it and have it be 
```
public class AdminLogin extends JFrame {
   ...
}
```

3)

> super("Login")

Each expression needs to end with a ';'. Meaning it's supposed to be `super("Login");`

> setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE;)
> setLayout(new GridLayout(3,2);

You need the same amount of opening and closing brackets. There's also a missing ; at the end. So it should be:

> setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
> setLayout(new GridLayout(3,2));

But that all the help I'm willing to give. This issue-tracker is dedicated to the WindowBuilder project and not a forum for general Java/Eclipse questions.

**Comment by pleasehelpmepoop** [comment]
im not that worried about it being in the wrong discussion (even tho both pertain to eclipse.ide so its not technically wrong) but thanks for the tips anyways.

**Comment by ptziegler** [comment]
I'm closing this issue, as it looks like a general Java question and not something related to the WindowBuilder.
