### ISSUE TITLE
Unable to parse source while tring to use JCalender

### ISSUE THREAD

**Issue by londonreturns** [eclipse-windowbuilder/windowbuilder#698]
<img width="1043" alt="Screenshot 2024-01-26 215721" src="https://github.com/eclipse-windowbuilder/windowbuilder/assets/76239421/f6efce53-8289-4c1e-a22d-9a4c9f53bbe9">

WindowBuilder not crashing everytime i try to use it. Auto generated code by windowbuilder

```
package utility;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

public class TEMPFRAME extends JFrame {

	private static final long serialVersionUID = 1L;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TEMPFRAME frame = new TEMPFRAME();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public TEMPFRAME() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
	}

}

```

**Comment by ptziegler** [comment]
> line: 13 The type com.toedter.calendar.JDateChooser is not accessible.

That looks a lot like compilation errors in your workspace.

Can you show me what the project looks like? Do you have a module-info.java file which is missing whatever module your custom JDateChooser is coming from?

**Comment by londonreturns** [comment]
> > line: 13 The type com.toedter.calendar.JDateChooser is not accessible.
> 
> That looks a lot like compilation errors in your workspace.
> 
> Can you show me what the project looks like? Do you have a module-info.java file which is missing whatever module your custom JDateChooser is coming from?

i added jcalender in module-info.java file, and it works fine 
<img width="379" alt="image" src="https://github.com/eclipse-windowbuilder/windowbuilder/assets/76239421/4d8a9e34-6d50-410c-b3f2-6e8920cd3400">

**Comment by ptziegler** [comment]
Alright then... this is the example I've set up.

I have the project _ModularProject1_, with a stub class _JCalendar_:

```
package test.jcalendar;

import javax.swing.JPanel;

public class JCalendar extends JPanel {
}
```

and the _module-info.java_:

```
module jcalendar {
	requires java.desktop;

	exports test.jcalendar;
}
```

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/14ffa7b1-365e-4e4a-a0d5-c04d580f3b01)

This class is used in a separate project called _ModularProject2_, where the _JCalendar_ is used by the class _MainFrame_:

```
package test;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import test.jcalendar.JCalendar;

public class MainFrame extends JFrame {

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					MainFrame frame = new MainFrame();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public MainFrame() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.add(new JCalendar());

		setContentPane(contentPane);
	}

}
```

and the _module-info.java_:

```
module ModularProject2 {
	requires java.desktop;
	requires jcalendar;
}
```

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/e2886f5b-c612-4549-946d-0c6d3ff25963)

Opening the _MainFrame_ class with the Design editor works without problem...

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/28e11da8-3e3d-4d82-8015-3739ba3824a6)

This tells me that there is no issue with how WindowBuilder handles the module system. Which makes be believe that there is something wrong with your projects and I therefore need to know what your workspace looks like, if you want me to help you.

As a slightly different question: What steps do you take that cause this error? Because the code snippet you show in your initial post doesn't reference the JDateChooser class and should open on its own.

**Comment by vanquanle** [comment]
![image](https://github.com/user-attachments/assets/cda09235-888b-4ff1-99ff-e5b41acb1d30)
lỗi này là sao vậy ạ

**Comment by ptziegler** [comment]
@vanquanle 

See:

> > > line: 13 The type com.toedter.calendar.JDateChooser is not accessible.
> > 
> > 
> > That looks a lot like compilation errors in your workspace.
> > Can you show me what the project looks like? Do you have a module-info.java file which is missing whatever module your custom JDateChooser is coming from?
> 
> i added jcalender in module-info.java file, and it works fine <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/76239421/300185691-4d8a9e34-6d50-410c-b3f2-6e8920cd3400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODY2MTQsIm5iZiI6MTcyMzQ4NjMxNCwicGF0aCI6Ii83NjIzOTQyMS8zMDAxODU2OTEtNGQ4YTllMzQtNmQ1MC00MTBjLWIzZjItNmU4OTIwY2QzNDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE4MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYjg3MzU3MDY2ZmFlYWMzMWI1MzViMGVjY2FkMDcxMjc1YTJiN2QwMDg4YjZlOGNmNDVjNjg0NzI4NTg3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98hfcSx3HGKM6MULjt7CheaYST2HtMJNWYOhnCfdryk">

You're likely using Java modules, so you either need to add `jcalendar` to your `module-info.java` file, or get rid of this file alltogether if you don't really need modules.

**Comment by ptziegler** [comment]
I'm closing this one as "won't fix". The issue most like was caused due to how the Java Platform Module System works.
