### ISSUE TITLE
WindowBuilder unexplained bug

### ISSUE THREAD

**Issue by ShizuVoice** [eclipse-windowbuilder/windowbuilder#709]
For some reason after updating both my Eclipse and the WindowBuilder, it seems it struggles to move or resize components from my active project that made me a bit frustrated that I cannot proceed with its current situation.

In this video, I tried to recreate the bug by doing my project again from scratch and that JPanel added to the designer triggered the bug. Any idea what happened? I can recreate this bug across Windows, macOS, and Linux.

https://github.com/eclipse-windowbuilder/windowbuilder/assets/65421364/1cfd5e2b-3d90-4657-b065-43b394f9aa5b

**Comment by ptziegler** [comment]
A similar bug was reported via #695.
Can you try out the latest milestone build?
https://download.eclipse.org/windowbuilder/updates/milestone/S202401292103

**Comment by ShizuVoice** [comment]
> A similar bug was reported via #695. Can you try out the latest milestone build? https://download.eclipse.org/windowbuilder/updates/milestone/S202401292103

So the bug was scrollbar related that prevents moving or resizing the components in the designer? That's something unexpected.

I tried your response and install the latest build of the WindowBuilder and it worked. Thank you for the update!


https://github.com/eclipse-windowbuilder/windowbuilder/assets/65421364/3cfc7cbf-18c9-4609-a9aa-88a2a7b1f14f
