### ISSUE TITLE
Java version not recognized

### ISSUE THREAD

**Issue by torjohn412** [eclipse-windowbuilder/windowbuilder#713]
Opening WindowBuilder editor for a WB-designed file, I get the following message:

**Incompatible Java versions**
"Eclipse is running under 17.01, but this Java project has a 21 Java compliance level, so WindowBuilder will not be able to load classes from this project. Use a lower level of Java for the project, or run Eclipse using a newer Java version."

Java version (in Eclipse settings):  Java SE 21.0.2   -- NOT 17.01 !!
Environment description:  Java SE 21
Running under MacOS on Apple silicon

What accounts for this?  How can I fix this?

**Comment by ptziegler** [comment]
> Eclipse is running under 17.01, but this Java project has a 21 Java compliance level

What's the value of your `java.home` environment variable?
In the `Help` menu, click `About` -> `About Eclipse IDE` -> `Installation Details`

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/0368a7a4-93b2-45bf-b241-124ba6eb0fcc)

Next click on the Configuration tab and filter for `java.home`

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/67a37de1-e70b-4bd4-aa76-142bc80b246e)

According to the error message, this should be Java 17.

---

Alternatively, you can also change the execution environment of your WindowBuilder project to Java 17. Right-click on the project, click `Properties` -> `Java Build Path`. In the `Libraries` tab, select the JRE in the module path, click edit and change it to Java 17.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/aad58a26-c4c1-4440-b87f-8f976e1ae6cb)

**Comment by torjohn412** [comment]
Thanks!

It was indeed Java 17 -- in a different folder (Applications/EclipseApp/... rather than Library/Java/..., which is where 21 was installed). I reinstalled Eclipse, and that worked.
