### ISSUE TITLE
Out-of-date SWT ResourceManager ??

### ISSUE THREAD

**Issue by torjohn412** [eclipse-windowbuilder/windowbuilder#715]
I am using an old com.swtdesigner.SWTResourceManager (worked on older Eclipse version) but cannot now find
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.Cursor;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.graphics.FontData;
import org.eclipse.swt.graphics.GC;
etc.

Is this obsolete code?  The packages no longer appear in the plugins list.

**Comment by ptziegler** [comment]
I'm closing this one. The `com.swtdesigner.SWTResourceManager ` has been replaced by the `org.eclipse.wb.swt.SWTResourceManager`. Though in general, I can only recommend using the JFace resource manager.
