### ISSUE TITLE
Modal dialog blocking design page from being opened

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder#741]
As discussed in #729 , opening a modal JDialog in another Swing component may cause the actual dialog being created, blocking WindowBuilder from switching to the design page. The user then has to manually close the dialog, in order to continue.

To reproduce:
```
public class MyFrame extends JFrame {
	public MyFrame() {
		new MyDialog();
	}

	public static class MyDialog extends JDialog {
		public MyDialog() {
			setModal(true);
			setVisible(true);
		}
	}
}
```

In general, we probably shouldn't create any instances of classes that extend Window, unless it's the root object...

**Comment by ptziegler** [comment]
@igarshep 

I've added your use case to our test suite and I've tested the changed with the code snippet you provided. Changes are high that WindowBuilder will no longer block when using the modal dialog. 🎉 
Can you check the upcoming nightly build again, to check whether this is the case?

In any case, thank you for reporting the problem, especially for debugging and providing the minimal reproducer!

**Comment by igarshep** [comment]
I'll verify, especially as I'm looking forward to this being fixed. Currently I'm having to comment out some buttons just to get into a design tab.

And thank you for how quick you are able to address the issue. Reporting/debugging couldn't have been as hard you the work you put in, so I seriously appreciate it!

**Comment by merks** [comment]
Such nice people. What goes around, comes around.
