### ISSUE TITLE
Cant maximize frame while Preview the frame

### ISSUE THREAD

**Issue by coderblu** [eclipse-windowbuilder/windowbuilder#751]
this is the issue with new window builder we cant maximize the preview panel but when we run the code then maximization is on, My colleague have previous version and it have that option
![Screenshot 2024-04-18 121355](https://github.com/eclipse-windowbuilder/windowbuilder/assets/118417802/4deeed6e-b96a-4d41-b4e6-74150db2e4e2)
![Screenshot 2024-04-18 121435](https://github.com/eclipse-windowbuilder/windowbuilder/assets/118417802/d58886a1-f57b-4bc3-abf2-194cd0bebb9d)

**Comment by ptziegler** [comment]
The "maximize" button has been disabled for technical reasons to allow capturing composites that are larger than the screen resolution. I've created #774 to make this mechanism more flexible, so it should be possible to use this button again, when the preview is opened.
