### ISSUE TITLE
Layout preference page doesn't keep default layout

### ISSUE THREAD

**Issue by dhmartin** [eclipse-windowbuilder/windowbuilder#785]
It seems like #640 and #641 that were fixed long time ago…

Preferences/WindowBuilder/Swing/layouts: setting default layout (as BorderLayout, but I also tried some others) is lost. Closing and reopening shows again "Implicit (default) layout"

We're using eclipse IDE JEE 2024-03 and tried to reproduce this on the most recent development versions of both eclipse and WindowBuilder (installed by dropins procedure)

- Eclipse JEE IDE 2024-06 M2 x64 for W10
- WindowBuilder-Updates-N202405231801

David

**Comment by ptziegler** [comment]
Fixed via #787. Thank you for reporting this issue!
