### ISSUE TITLE
Windowbuilder on Linux Mint XFCE: drop-down selector obscured by vertical scroll bar

### ISSUE THREAD

**Issue by MHNixon** [eclipse-windowbuilder/windowbuilder#795]
Please forgive this newbie if the above issue has already been solved!
For some 10 years I have been using Eclipse with Windowbuilder to write java apps.
However with the last couple of updates I've noticed that when I try to change a swing objects properties in the designer, the vertical scrollbar almost completely obscures the drop-down triangle. Only with careful mouse positioning can I get at the icon and change a property.  The attached screenshot should hopefully clarify my issue.
I've tried several command line and environment settings relating to GTK without any success.  
[Linux Mint 21 XFCE]
I do hope someone can assist!
![eclipse_windowbuilder_issue](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/a6abd509-bc2e-41c8-8bf9-48a9a7b58f11)
![about_eclipse](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/a107e718-852c-4a3f-96e2-11f8c91f000d)

**Comment by ptziegler** [comment]
Out of curiosity, can you try out whether the same issue happens with the upcoming Eclipse version? The ide should drop sometime tomorrow. There is an issue with how scrollbars are rendered in GEF (the backend of the property table) on GTK, which isn't included in the current release.

See: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1182

**Comment by ptziegler** [comment]
When overlay scrolling is enabled, it's also quite a pain to use... 

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/8d5d85d2-2bb2-48f8-bc50-c1ac8a69c737)

I think it makes sense to force the scrollbar to show up. Then this should sort itself out.

**Comment by MHNixon** [comment]
Thanks for the feedback, Patrick.  Seems a "thinner" semi-transparent
scrollbar,   or forcing a re-sizing what of objects is what window builder
needs in this particular context.  Surprised that the dropdown list boxes
don't shrink to accomodate the scrollbar. Scrollbar issue only manifests
itself when you click the "advanced properties" icon.
Mike Nixon
+27 82 456 1152
[sent from my cellphone]

**Comment by ptziegler** [comment]
Fixed via #803 and https://github.com/eclipse/gef-classic/pull/459. Overlay scrolling has been disabled in general, as the buttons might otherwise be obscured.

@MHNixon Can you check out the upcoming nightly build and see whether this issue still occurs? Also note that this requires changes introduced with the latest GEF nightly build.

Unrelated, but you might want to consider removing/editing your previous post. I don't really understand why GitHub thought it's appropriate to post your phone number...

**Comment by MHNixon** [comment]
Latest Windowbuilder nightly with Eclipse 2024-03 broken.
I have downloaded Eclipse 2024-06 & will install this & test again.

<code>
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.rngdatatype.helpers.ProxyDatatypeLibraryFactory of service com.sun.tools.rngdatatype.DatatypeLibraryFactory in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.code_injector.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.locator.SourceLocationAddOn of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.sync.SynchronizedMethodAddOn of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.at_generated.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.episode.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider com.sun.tools.xjc.addon.accessors.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
Jun 20, 2024 6:31:52 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.glassfish.jaxb.runtime.v2.JAXBContextFactory of service jakarta.xml.bind.JAXBContextFactory in bundle com.sun.xml.bind.jaxb-osgi
Exception in thread "org.eclipse.jdt.internal.ui.text.JavaReconciler" java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.IWorkbenchWindow.getShell()" because the return value of "org.eclipse.ui.internal.PartSite.getWorkbenchWindow()" is null
	at org.eclipse.ui.internal.PartSite.getShell(PartSite.java:441)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.reconciled(CompilationUnitEditor.java:1690)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconciled(JavaReconcilingStrategy.java:228)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconciled(JavaCompositeReconcilingStrategy.java:171)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:147)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:100)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:421)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:177)
</code>
![Windowbuilder_error](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/3fcca01a-b4d2-49bc-9280-10efbe91f967)
![windowbuilder_nightly](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/b14b36bb-253e-425e-983b-73ab16e84a90)

**Comment by ptziegler** [comment]
WindowBuilder depends on the latest version of SWT, in order to use the method introduced with https://github.com/eclipse-platform/eclipse.platform.swt/commit/eb0f99db46d5ee8f6c345d8a3096efb401b41a03.

This method doesn't exist in the 2024-03. I've created https://github.com/eclipse-windowbuilder/windowbuilder/pull/804 to raise the lower bound, to reflect this dependency.

**Comment by MHNixon** [comment]
1. completely removed Eclipse 2024-03, .p2, config files
2. tried running Eclipse 2024-06 installer, but it kept timing out
3. Removed OpenJDK 17
4. Installed OpenJDK 21
5. Downloaded & installed Eclipse Runtime 2024-06
6. Can not update: "this installation has not been configured for software updates..."
7. Can not install Windowbuilder: "profile _SELF_ is not registered...."

This is way too much trouble trying to install Eclipse, so I have decided to abandon Eclipse altogether & switch to Netbeans: it just works out of the box without all these problems.   
Thank you for your efforts, though: much appreciated.  It seems Eclipse is not really recommended for Linux platforms based on my experience. [Linux Mint 21 XFCE].  I have used various versions of Eclipse since 2008, mostly with success, but at age 76 I haven't enough years left to spend just trying to get something to install correctly. 
<code>
~/eclipse$ ./eclipse
WARNING: Using incubator modules: jdk.incubator.vector
Jun 20, 2024 7:15:13 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
19:15:16.037 [Start Level: Equinox Container: 6515c989-6192-4020-8601-82eeef568717] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- register org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x00007f65901ea608@1c13fafb with shutdown hook
19:15:16.037 [Start Level: Equinox Container: 6515c989-6192-4020-8601-82eeef568717] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- register org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x00007f65901ea608@1c13fafb with shutdown hook
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
</code>
![Screenshot_2024-06-20_19-18-26](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/a9d70a02-0c62-4166-a754-6e322ef17d07)
![Screenshot_2024-06-20_19-19-11](https://github.com/eclipse-windowbuilder/windowbuilder/assets/134629201/cecaf2ef-362e-4ec5-bebc-4fd33d38ac92)
