### ISSUE TITLE
Error when trying to use JCalendar

### ISSUE THREAD

**Issue by Pedro101520** [eclipse-windowbuilder/windowbuilder#811]
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/105872928/ac947ae5-ecbe-4dc4-a649-0f20809ca0d3)

When I try to add an element to JCalendar, this error appears

**Comment by ptziegler** [comment]
Can you provide a small example or a little bit more detail on what exactly your workspace looks like?

The error itself seems to suggest that the JCalendar jar you're using is not part of the Java classpath. But without further information, I can't make any assumptions about what exactly goes wrong here.

I tried out the demo that is shipped with JCalendar which at first glance seems to work. So I don't think there is an inherent problem.
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/b12755da-682e-40b0-bded-f7c4001976a6)

**Comment by Pedro101520** [comment]
Thanks for answering!
I managed to fix it by adding the following code in the module-info.java file: requires jcalendar;
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/105872928/c6553665-ad13-47bd-b928-a80f7af4c876)
