### ISSUE TITLE
Drop support for Swing Application Framework (jsr 296)

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder#887]
This JSR has been withdrawn back in [2011](https://jcp.org/en/jsr/detail?id=296), the project page is offline and the most recent jars on Maven Central are from 2010.

The project is officially dead and we don't even test it, due to a lack of jars.  And as far as I can tell, all major projects have long moved to different frameworks, so I don't see much point in continuing to support it.

**Comment by ptziegler** [comment]
In addition, the current support is rudimentary, at best. We can read some applications, but we can't even create new ones.

**Comment by vogella** [comment]
+1 for removal, thanks @ptziegler
